---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install NodeJs
        uses: actions/setup-node@v3
        with: 
          node-version: '14'

      - name: install Dependencies
        run: yarn install

      - name: linting
        run: yarn lint

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: waneraren/webapp:latest
#test2